# Generated by Django 4.1.2 on 2022-11-03 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='Correo electronico')),
                ('date_created', models.CharField(max_length=30)),
                ('idTec', models.CharField(max_length=13, verbose_name='No. Control o RFC')),
                ('nombre', models.CharField(max_length=35, null=True, verbose_name='Nombre(s)')),
                ('aPaterno', models.CharField(max_length=35, null=True, verbose_name='Apellido Paterno')),
                ('aMaterno', models.CharField(max_length=35, null=True, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(max_length=10, null=True, verbose_name='Telefono')),
                ('fotoDePerfil', models.ImageField(default='default_pic.jpg', upload_to='profile_pics')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=2, null=True)),
                ('tipouser', models.CharField(choices=[('T_O', 'Tutorado'), ('T_R', 'Tutor'), ('JDE', 'Jefe de departamento academico'), ('CDT', 'Coordinador de tutoria (departamento academico)'), ('CIT', 'Coordinacion institucional de tutoria'), ('JDO', 'Jefe de docencia (Creditos complementarios)'), ('SUB', 'Subdirector'), ('PSI', 'Psicologo'), ('MED', 'Medico')], default='TU', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fechaDeAsignacion', models.DateField()),
                ('fechaDeCierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('fecha', models.DateField()),
                ('encargado', models.CharField(max_length=50)),
                ('cantTutorados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Depertamento')),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('R', 'Retrasado')], max_length=1)),
                ('fechaDeEnvio', models.DateField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13)),
                ('constancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=50, null=True)),
                ('localizacion', models.CharField(max_length=50, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='QuejaSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estado', models.CharField(choices=[('L', 'Leido'), ('N', 'No Leido')], max_length=1)),
                ('fechaDeCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tecnologico')),
                ('entidadFed', models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DIF', 'Distrito Federal'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('MEX', 'Estado de México'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TIA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=3, null=True, verbose_name='Entidad Federativa')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeNacimiento', models.DateField(null=True)),
                ('curp', models.CharField(max_length=18, null=True)),
                ('estadoCivil', models.CharField(choices=[('SO', 'Soltero'), ('CA', 'Casado')], max_length=2, null=True)),
                ('nss', models.CharField(max_length=15, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('semestre', models.IntegerField(null=True)),
                ('estatus', models.CharField(choices=[('ACT', 'Activo'), ('EXP', 'Expulsado')], max_length=3, null=True)),
                ('entidadFed', models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHP', 'Chiapas'), ('CHH', 'Chihuahua'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DIF', 'Distrito Federal'), ('DUR', 'Durango'), ('GUA', 'Guanajuato'), ('GRO', 'Guerrero'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('MEX', 'Estado de México'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TIA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=3, null=True)),
                ('municipio', models.CharField(max_length=50, null=True)),
                ('domicilio', models.CharField(max_length=50, null=True)),
                ('cp', models.IntegerField(null=True)),
                ('contactConfianza', models.CharField(max_length=50, null=True)),
                ('tecDeProcedencia', models.IntegerField(null=True)),
                ('carrera', models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.carrera')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.grupo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('R', 'Retrasado')], max_length=1)),
                ('fechaLimite', models.DateField()),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.archivo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.personal')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.personal'),
        ),
        migrations.CreateModel(
            name='Entregas_Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.archivo')),
                ('entregas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.entregas')),
            ],
        ),
        migrations.AddField(
            model_name='entregas',
            name='tutorado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.tutorado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.tecnologico', verbose_name='Tecnologico al que pertenece'),
        ),
        migrations.CreateModel(
            name='CreditosTutorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(null=True)),
                ('estado', models.CharField(choices=[('1', 'En espera'), ('2', 'Aceptado'), ('3', 'Rechazado')], max_length=1)),
                ('fechaDeEnvio', models.DateField()),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.curso')),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.archivo')),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.tutorado')),
            ],
        ),
        migrations.CreateModel(
            name='Creditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeValidacion', models.DateField()),
                ('creditostutorado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sgt.creditostutorado')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.personal', verbose_name='Quien valido')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Psicologo'), ('M', 'Medico')], max_length=1)),
                ('motivos', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('fechaDeCita', models.DateField()),
                ('fechaDeCreacion', models.DateField()),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.personal')),
                ('tutorado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.tutorado')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sgt.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.tecnologico', verbose_name='Tecnologico'),
        ),
        migrations.CreateModel(
            name='Actividad_Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.actividad')),
                ('archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.archivo')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.grupo'),
        ),
    ]
