# Generated by Django 4.1.2 on 2022-11-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0002_personal_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='personal',
        ),
        migrations.AddField(
            model_name='personal_carrera',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.grupo'),
        ),
    ]
