# Generated by Django 4.1.2 on 2022-11-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0003_remove_grupo_personal_personal_carrera_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='fechaDeEnvio',
            field=models.DateField(blank=True),
        ),
    ]
