# Generated by Django 4.1 on 2022-12-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0008_carrera_nomenclatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='descripcionCita',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='fechaDeCita',
            field=models.DateField(null=True),
        ),
    ]
