# Generated by Django 4.1 on 2022-12-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0009_alter_myuser_tipouser'),
        ('sgt', '0009_citas_descripcioncita_alter_citas_fechadecita'),
    ]

    operations = [
    ]
