# Generated by Django 4.1 on 2022-12-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0011_alter_myuser_tipouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_carrera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
