# Generated by Django 4.1 on 2022-12-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0012_personal_carrera_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermina', models.DateField()),
                ('tipoPeriodo', models.CharField(choices=[('1', 'Invierno'), ('2', 'Otoño'), ('3', 'Verano')], max_length=1)),
            ],
        ),
    ]
