# Generated by Django 4.1 on 2022-12-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0013_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditostutorado',
            name='folio',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
