# Generated by Django 4.1 on 2022-12-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0014_creditostutorado_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditostutorado',
            name='folio',
        ),
        migrations.AddField(
            model_name='curso',
            name='folio',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
