# Generated by Django 4.1 on 2022-12-06 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0016_remove_creditostutorado_valor_curso_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoGrupal', models.IntegerField()),
                ('tutoIndividual', models.IntegerField()),
                ('canalizados', models.IntegerField()),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('asistencia', models.IntegerField()),
                ('Tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.personal')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.grupo')),
                ('noControl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteJDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoGrupal', models.IntegerField()),
                ('tutoIndividual', models.IntegerField()),
                ('canalizados', models.IntegerField()),
                ('area', models.CharField(max_length=30, null=True)),
                ('jda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.personal')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.personal_carrera')),
            ],
        ),
    ]
