# Generated by Django 4.1 on 2022-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0016_remove_creditostutorado_valor_curso_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
