# Generated by Django 4.1 on 2022-12-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0017_cursopendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditostutorado',
            name='cursoPendiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.cursopendiente'),
        ),
    ]
