# Generated by Django 4.1 on 2022-12-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0017_reportetutor_reportejda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportetutor',
            name='asistencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportetutor',
            name='canalizados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportetutor',
            name='tutoGrupal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportetutor',
            name='tutoIndividual',
            field=models.IntegerField(null=True),
        ),
    ]
