# Generated by Django 4.1 on 2022-12-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0018_creditostutorado_cursopendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
