# Generated by Django 4.1 on 2022-12-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0018_alter_reportetutor_asistencia_and_more'),
        ('sgt', '0019_alter_curso_valor'),
    ]

    operations = [
    ]
