# Generated by Django 4.1 on 2022-12-08 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0021_alter_myuser_tipouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='fechaDeEnvio',
            field=models.DateField(default=datetime.datetime(2022, 12, 8, 0, 11, 38, 624069)),
        ),
    ]
