# Generated by Django 4.1 on 2022-12-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0022_reportes_fechadeenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fechaDeEnvio',
            field=models.DateField(),
        ),
    ]
