# Generated by Django 4.1 on 2022-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0023_alter_reportes_fechadeenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='motivos',
            field=models.CharField(max_length=256),
        ),
    ]
