# Generated by Django 4.1 on 2022-12-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0024_reportes_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgt.personal_carrera'),
        ),
    ]
