# Generated by Django 4.1 on 2022-12-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0026_alter_reportes_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='grupo',
        ),
    ]
