# Generated by Django 4.1 on 2022-12-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0027_remove_reportes_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='reporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgt.reportes'),
        ),
    ]
