# Generated by Django 4.1 on 2022-12-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgt', '0024_alter_citas_motivos'),
        ('sgt', '0028_grupo_reporte'),
    ]

    operations = [
    ]
